version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gym_postgres
    environment:
      - POSTGRES_USER=gatoro
      - POSTGRES_PASSWORD=твой_пароль
      - POSTGRES_DB=gym_db
    ports:
      - "5433:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: gym_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env